src/web/GS.WebApp.MVC/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using GS.WebApp.MVC.Models;
using GS.WebApp.MVC.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.IdentityModel.Tokens.Jwt;

namespace GS.WebApp.MVC.Controllers;

public class AuthenticationController : AbstractController
{
    private readonly IAuthService _service;

    public AuthenticationController(IAuthService service) => _service = service;

    [HttpGet]
    [Route("signup")]
    public IActionResult Signup() => View();

    [HttpPost]
    [Route("signup")]
    public async Task<IActionResult> Signup(UserCreate user)
    {
        if (!ModelState.IsValid) return View(user);
        var response = await _service.Signup(user);
        if (ResponseErrors(response.ResponseResult)) return View(user);
        await Login(response);
        return RedirectToAction(actionName: "Index", controllerName: "Home");
    }

    [HttpGet]
    [Route("signin")]
    public IActionResult Signin(string? returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        return View();
    }

    [HttpPost]
    [Route("signin")]
    public async Task<IActionResult> Signin(UserLogin user, string? returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        if (!ModelState.IsValid) return View(user);
        var response = await _service.Signin(user);
        if (ResponseErrors(response.ResponseResult))
        {
            return View(user);
        }
        await Login(response);
        if(string.IsNullOrEmpty(returnUrl))
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        return LocalRedirect(returnUrl);
    }

    [HttpGet]
    [Route("signout")]
    public async Task<IActionResult> Signout()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToAction(actionName: "Index", controllerName: "Home");
    }

    private async Task Login(UserResponse response)
    {
        var token = FormatedToken(response.AccessToken);
        var claims = new List<Claim>();
        claims.Add(new Claim(type: "JWT", value: response.AccessToken)); //just to remenber the token
        claims.AddRange(token.Claims);
        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
        var authproperties = new AuthenticationProperties
        {
            ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
            IsPersistent = true
        };
        await HttpContext.SignInAsync(
            scheme: CookieAuthenticationDefaults.AuthenticationScheme,
            principal: new ClaimsPrincipal(claimsIdentity),
            properties: authproperties
        );
    }

    private static JwtSecurityToken FormatedToken(string jwtToken)
    {
        return new JwtSecurityTokenHandler().ReadToken(jwtToken) as JwtSecurityToken;
    }


}

src/web/GS.WebApp.MVC/Extensions/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace GS.WebApp.MVC.Extensions;

public class SummaryViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync()
    {
        return View();
    }
}

src/web/GS.WebApp.MVC/Views/Authentication/Signin.cshtml
@model GS.WebApp.MVC.Models.UserLogin

@{
    ViewData["Title"] = "Sign In";
}

<h1>@ViewData["Title"]</h1>
<div class="row">
    <div class="col-md-12">
        <section>
            <form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <h4>Welcome back, My Dear!</h4>
                <hr>
                <vc:summary></vc:summary>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input type="email" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input type="password" asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Log In</button>
                </div>
                <div class="form-group">
                    <p>
                        No account? <a asp-action="Signup" asp-controller="Authentication">Create one!</a>
                    </p>
                </div>
                <hr>
            </form>
        </section>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

src/web/GS.WebApp.MVC/Views/Authentication/Signup.cshtml
@model GS.WebApp.MVC.Models.UserCreate

@{
    ViewData["Title"] = "Sign Up";
}

<h1>@ViewData["Title"]</h1>
<div class="row">
    <div class="col-md-12">
        <section>
            <form method="post">
                <h4>Create free Account</h4>
                <hr>
                <vc:summary></vc:summary>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input type="email" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input type="password" asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <label asp-for="PasswordConfirmation"></label>
                    <input type="password" asp-for="PasswordConfirmation" class="form-control" />
                    <span asp-validation-for="PasswordConfirmation" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
                <hr>
            </form>
        </section>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}